### ISSUE TITLE
Organize this repo

### ISSUE THREAD

**Issue by pmwhite** [CedarvilleAsee/Columbot2017#2]
This repository is becoming slightly disorganized. It's not a big issue, but since I have free time, and I'm not working on anything else, I thought I would start this.

Things that would make it better:
- Flatten folder structures so that all the files are on the root directory. We don't have enough files that putting them in folders is necessary; having folders at this point is inconvenient because it cause people to have to do extra navigation. In the future, if/when we have more files, we can reorganize, but for now, we shouldn't over-organize.
- Consolidate documentation files. We currently have three files, including a `TentativeStates`, `Documentation`, and the `README.md`. They're all short enough that we can just put them all into the `README.md`.
- Building on the previous point, we should be documenting what functionality is in which files. This would let us find things without looking through a bunch of folders and files for a piece of code. In addition, we can keep all of our documentation for how to set up the robot, and what websites to go to for information such as pin numbers, board layou, etc.
- Clean up files, or else document what's going on. The code files we have contain a lot of commented out pieces of code. We should either clean up code that we don't want, or we should make comments telling what certain parts of code are doing, and why it was commented out. At the top of files, we should have comments telling what is supposed to be accomplished by the whole file. At this point, we don't have much solid and finished code, so having a lot of commented out stuff is understandable. However, making informative, clear, and concise comments would make these files easier to navigate.
- Establish how we are going to handle committing to this repo. The github workflow involves having a separate fork for every user, and then each user can submit a pull request when he has finished a certain piece of code. Right now, we've just been committing everything directly to the repo. This is fine for now, and it could be fine for the whole project, but it would be worth having at least a short discussion about it when we start getting into a lot of coding.

Discussion is of course welcome. I can most of what I said, so I'll submit a pull request when it is ready.

**Comment by Bombadad** [comment]
I see that this would be a good idea. The commented code is the the old code that we are not using from Sonic and Tails.  To not have to build from scratch I thought that it would be a good idea to re-use code.  However, that has turned out to not be as good of an idea as I had thought.

Also, a note on Arduino.  In order to use a .ino file it must be inside a folder of the same name.

**Comment by pmwhite** [comment]
Oh, okay. I didn't know about the arduino files needing to be in a directory. When we start making the actual final code, we're not gonna have this problem, correct?

Don't worry about doing the stuff; I should have time today to do it. When I'm finished, I'll submit a pull request.
